### ISSUE TITLE
Missing Package qcrilhook + LOGCAT Base + GSI

### ISSUE THREAD

**Issue by xdsurvivor** [ZJRDroid/vendor_motorola_cedric#1]
cedric_vendor.mk
add qcrillhook \ 
at line 1032

LOGCAT:
[logcat.log](https://github.com/ZJRDroid/vendor_motorola_cedric/files/3243899/logcat.log)

(https://github.com/ZJRDroid/vendor_motorola_cedric/files/3243898/logcat_06-01-2019_13-13-09.txt)

**Comment by ZJRDroid** [comment]
Fixes!
